[[redirects]]
        from = "/aktualnosci-publikacje/umowa-o-prace-charakterystyka/"
        to = "/blog/artykul/umowa-o-prace-charakterystyka/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/zdolnosc-do-czynnosci-prawnych/"
        to = "/blog/artykul/czym-jest-zdolnosc-do-czynnosci-prawnych/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/rodzaje-posiedzen-sadowych/"
        to = "/blog/artykul/rodzaje-posiedzen-sadowych/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/zabezpieczenia-banknotow/"
        to = "/blog/artykul/zabezpieczenia-banknotow/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/ubezpieczenie-oc-pojazdow-obowiazki-i-kary-finansowe/"
        to = "/blog/artykul/ubezpieczenie-oc-pojazdow-obowiazki-i-kary-finansowe/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/listy-polecone-odbierac-czy-nie-odbierac/"
        to = "/blog/artykul/listy-polecone-odbierac-czy-nie-odbierac/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/co-z-wyplata-swiadczenia-rodzina-500-gdy-jeden-z-rodzicow-pracuje-za-granica-a-drugi-z-malzonkow-pracuje-i-mieszka-z-dziecmi-w-polsce/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/obowiazek-alimentacyjny-czy-pandemia-wirusa-covid-19-go-zmienia/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/rozporzadzenia-covidowe-a-legalnosc-zakazu-prowadzenia-dzialalnosci-gospodarczej-oraz-kwarantanny/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/jak-sie-rozwiesc-bez-bolu-glowy/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/czy-przedsiebiorca-moze-byc-traktowany-jak-konsument/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/jak-uzyskac-odpis-wyroku/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/jazda-na-podwojny-gazie-co-ci-grozi/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/prawo-jazdy/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/zwrot-towaru-krotki-poradnik-o-prawach-kupujacego/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/slub-i-wesele-w-dobie-covid-19/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/odszkodowanie-dla-personelu-medycznego-za-zakazenie-sie-koronawirusem-covid-19/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/tarcza-antykryzysowa-20-krotki-poradnik-przedsiebiorcy/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/jak-sie-odizolowac-od-przemocy-w-rodzinie/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/tarcza-antykryzysowa-10-praktyczny-poradnik/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/wycieczka-z-biurem-podrozy-w-czasach-pandemii-koronawirusa/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/realizacja-kontaktow-z-dzieckiem-w-czasach-pandemii-koronawirusa/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/masz-kredyt-we-frankach-to-czas-dla-ciebie/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/kredytobiorca-nieslusznie-wskazany-w-bik-jako-dluznik-co-dalej/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/odszkodowania-za-halas-z-lotniska-wojskowego-w-lasku-tylko-do-6-grudnia-2018-roku/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/nowa-strefa-wokol-lotniska-wojskowego-w-lasku-zostala-uchwalona/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/nienalezne-oprocentowanie-kredytu-oraz-waloryzacja-kwoty-kredytu-a-waznosc-umowy-kredytowej/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/kredytobiorca-a-zwrot-ubezpieczenia-niskiego-wkladu/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/zmiany-w-prawie-od-lipca-2015r/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/dodatkowe-informacje/witamy/"
        to = "/"
        status = 301
        force = false
[[redirects]]
        from = "/zespol/"
        to = "/kancelaria/"
        status = 301
        force = false
[[redirects]]
        from = "/aktualnosci-publikacje/"
        to = "/blog/"
        status = 301
        force = false
[[redirects]]
        from = "/specjalizacje/nieruchomosci-i-spadki/"
        to = "/specjalizacje/"
        status = 302
        force = false
[[redirects]]
        from = "/specjalizacje/biznes/"
        to = "/specjalizacje/b2b/"
        status = 301
        force = false
[[redirects]]
        from = "/specjalizacje/prawo-karne/"
        to = "/specjalizacje/"
        status = 302
        force = false
[[redirects]]
        from = "/specjalizacje/rozwody/"
        to = "/specjalizacje/sprawy-rozwodowe/"
        status = 301
        force = false
[[redirects]]
        from = "/rodo/"
        to = "/"
        status = 302
        force = false
[[redirects]]
        from = "/dodatkowe-informacje/adres/"
        to = "/kontakt/"
        status = 301
        force = false
[[redirects]]
        from = "/zespol/*"
        to = "/kancelaria/"
        status = 301
        force = false